name: Create Release and Publish to PyPI

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  create-release-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools

    - name: Get version
      id: get_version
      run: |
        version=$(python setup.py --version)
        echo "VERSION=$version" >> $GITHUB_OUTPUT

    - name: Check if tag exists
      id: check_tag
      run: |
        if [ $(git tag -l "v${{ steps.get_version.outputs.VERSION }}") ]; then
          echo "Tag exists"
          echo "TAG_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "Tag does not exist"
          echo "TAG_EXISTS=false" >> $GITHUB_OUTPUT
        fi

    - name: Create and push tag
      if: steps.check_tag.outputs.TAG_EXISTS == 'false'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag v${{ steps.get_version.outputs.VERSION }}
        git push origin v${{ steps.get_version.outputs.VERSION }}

    - name: Create Release
      if: steps.check_tag.outputs.TAG_EXISTS == 'false'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Build package
      run: python -m build

    - name: Publish distribution to PyPI
      if: steps.check_tag.outputs.TAG_EXISTS == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
